# Generated by Django 5.1.7 on 2025-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
