# Generated by Django 5.1.7 on 2025-04-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_imageurl_listing_image_url_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
    ]
