# Generated by Django 5.1.7 on 2025-04-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='created_at',
        ),
    ]
